---
- name: "Déploiement de l'application sur Kubernetes"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    docker_image: "{{ docker_image }}"
    image_tag: "{{ image_tag }}"
    app_name: "devops-tp-app"

  tasks:

    - name: "Appliquer le Deployment"
      shell: |
        sed 's|IMAGE_PLACEHOLDER|{{ docker_image }}:{{ image_tag }}|g' \
          k8s/deployment.yaml | \
        kubectl apply -f - -n devops-tp
      ignore_errors: true

    - name: "Appliquer le Service"
      shell: kubectl apply -f k8s/service.yaml -n devops-tp
      ignore_errors: true

    - name: "Afficher les pods"
      shell: kubectl get pods -n devops-tp
      ignore_errors: true
      register: pods

    - name: "Show pods"
      debug:
        msg: "{{ pods.stdout }}"